version: '3.7'

services:
  nginx:
    build:
      context: ./
      target: vcweb_nginx
    image: ${NGINX_IMAGE:-vcweb/nginx}
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    networks:
      frontend:
        aliases:
          - nginx

networks:
  frontend:
    driver: bridge
