version: '3.7'

services:
  nginx:
    build:
      context: ./
      target: vcweb_nginx
    image: ${NGINX_IMAGE:-vcweb/nginx}
    volumes:
      - .:/var/www/html
    ports:
      - "880:80"
    networks:
      frontend:
        aliases:
          - nginx
  haproxy:
    build:
      context: ./
      target: vcweb_haproxy
    image: ${HAPROXY_IMAGE:-vcweb/haproxy}
    depends_on:
      - nginx
    ports:
      - "80:80"
      - "9000:9000"
    networks:
      frontend:
        aliases:
            - haproxy

networks:
  frontend:
    driver: bridge
